version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-your_database}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      CHOKIDAR_USEPOLLING: true
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: your_database
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  db_data: